// src/drugData.js// เราจะแปลงข้อมูลยาให้อยู่ในรูปแบบที่ JavaScript เข้าใจง่าย// 
// โดยเฉพาะ DrugConcentration เราจะแยกตัวเลขออกมาเลย
export const drugList = [
  {
    id: 1,
    name: 'Amoxycillin (250mg/5ml)',
    concentration: 250, // mg
    volume: 5,          // ml
    minDosePerKg: 10,
    maxDosePerKg: 16.7,
    notes: 'รับประทานหลังอาหาร วันละ 3 ครั้ง (กินติดต่อกันจนยาหมด)',
  },
  {
    id: 2,
    name: 'Augmentin (228.5mg/5ml)',
    concentration: 228.5,
    volume: 5,
    minDosePerKg: 12.5,
    maxDosePerKg: 22.5,
    notes: 'รับประทานหลังอาหาร วันละ 2 ครั้ง (กินติดต่อกันจนยาหมด)',
  },
  {
    id: 3,
    name: 'Bactrim (40mg/5ml)',
    concentration: 40,
    volume: 5,
    minDosePerKg: 3,
    maxDosePerKg: 6,
    notes: 'รับประทานหลังอาหาร วันละ 2 ครั้ง (กินติดต่อกันจนยาหมด)',
  },
  {
    id: 4,
    name: 'CPM (2mg/5ml)',
    concentration: 2,
    volume: 5,
    minDosePerKg: 0.12,
    maxDosePerKg: 0.12, // Min กับ Max เท่ากัน
    notes: 'รับประทานหลังอาหาร วันละ 3 ครั้ง (กินติดต่อกันจนยาหมด)',
  },
  {
    id: 5,
    name: 'Dicloxacillin (62.5mg/5ml)',
    concentration: 62.5,
    volume: 5,
    minDosePerKg: 3.125,
    maxDosePerKg: 6.25,
    notes: 'รับประทานก่อนอาหาร วันละ 4 ครั้ง (กินติดต่อกันจนยาหมด)',
  },
  {
    id: 6,
    name: 'Domperidone (5mg/5ml)',
    concentration: 5,
    volume: 5,
    minDosePerKg: 0.2,
    maxDosePerKg: 0.4,
    notes: 'รับประทานก่อนอาหาร วันละ 3 ครั้ง',
  },
  {
    id: 7,
    name: 'Erythromycin (125mg/5ml)',
    concentration: 125,
    volume: 5,
    minDosePerKg: 7.5,
    maxDosePerKg: 12.5,
    notes: 'รับประทานก่อนอาหาร วันละ 4 ครั้ง (กินติดต่อกันจนยาหมด)',
  },
  {
    id: 8,
    name: 'Guafenesine (100mg/5ml)',
    concentration: 100,
    volume: 5,
    minDosePerKg: 2.5,
    maxDosePerKg: 5,
    notes: 'รับประทานหลังอาหาร วันละ 3 ครั้ง',
  },
  {
    id: 9,
    name: 'Ibuprofen (100mg/5ml)',
    concentration: 100,
    volume: 5,
    minDosePerKg: 5,
    maxDosePerKg: 10,
    notes: 'รับประทานหลังอาหาร วันละ 3 ครั้ง (กินยาหลังอาหารทันที)',
  },
  {
    id: 10,
    name: 'Paracetamol (120mg/5ml)',
    concentration: 120,
    volume: 5,
    minDosePerKg: 10,
    maxDosePerKg: 15,
    notes: 'ให้ทุก 4-6 ชั่วโมง',
  },
];